### ISSUE TITLE
Power Status Update When Manually Switching on Heater

### ISSUE THREAD

**Issue by tmur11** [spin877/Bruciatore_BLE#8]
After manually powering on the heater, the power switch status is not showing correctly in homeassisant. Oddly the log does show the change of power status. Don't mind the naming of Kitchen Presence just using an old ESP for testing

![image](https://github.com/user-attachments/assets/4224e33d-2352-4e2b-8354-69627251672d)

**Comment by DanClarke-io** [comment]
I ended up adding this automation, which may help you:
```
alias: Set heating to off when power at 0
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.power_status
    for:
      hours: 0
      minutes: 1
      seconds: 0
    below: 1
conditions:
  - condition: state
    entity_id: switch.heater_power
    state: "on"
actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.heater_power
mode: single

```
